name: learn1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  
  # For working with assets (e.g., loading images)
  flutter_svg: ^0.22.0
  
  # For using base64 encoding/decoding for image and data handling
  crypto: ^3.0.1
  
  # Package to enable handling image data and manipulation (optional if needed)
  image: ^3.0.1

  # Bluetooth printer support (if you're using bluetooth_print_plus for printing)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_image.png
