name: learn1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils: ^1.0.0 # or the latest version
  flutter_blue: ^0.8.0 # Keep your existing packages
  image: ^3.0.1 # For manipulating image files

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_image.png
